#[theme]
#primaryColor="#3872fb"
#backgroundColor="#0e1117"
#secondaryBackgroundColor="#cece1b"
#textColor="#fafafa"
#font="sans serif"
 
[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
